#ifndef ULTRAVIOLET_CONSTANTS_H_
#define ULTRAVIOLET_CONSTANTS_H_

const float BOLTZMANN_CONSTANT_W_PER_m2_K4 = 5.670373e-8;
const float GRAVITATIONAL_CONSTANT_m3_PER_kg_s2 = 6.6743e-11;
const float SPEED_OF_LIGHT_m_PER_s = 299792458.0;
const float SCHWARZSCHILD_FACTOR_m_PER_kg = 2.0 * GRAVITATIONAL_CONSTANT_m3_PER_kg_s2 / pow(SPEED_OF_LIGHT_m_PER_s, 2.0);

#endif