plugins {
	id 'fabric-loom' version '0.12-SNAPSHOT'
	id 'maven-publish'
}

sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17

archivesBaseName = project.archives_base_name
version = project.mod_version
group = project.maven_group

repositories {
	// Add repositories to retrieve artifacts from in here.
	// You should only use this when depending on other mods because
	// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	// See https://docs.gradle.org/current/userguide/declaring_repositories.html
	// for more information about repositories.
	maven {
		url "https://maven.parchmentmc.org"
	}
    maven {
        name = 'Ladysnake Mods'
        url = 'https://maven.ladysnake.org/releases'
    }
}

loom {
	accessWidenerPath = file("src/main/resources/ultraviolet.accesswidener")
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.layered() {
		officialMojangMappings()
		parchment("org.parchmentmc.data:parchment-${project.minecraft_version}:${project.parchment_version}@zip")
	}
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    modImplementation include("dev.onyxstudios.cardinal-components-api:cardinal-components-base:${project.cardinal_components_version}")
    modImplementation include("dev.onyxstudios.cardinal-components-api:cardinal-components-scoreboard:${project.cardinal_components_version}")
    modImplementation include("dev.onyxstudios.cardinal-components-api:cardinal-components-world:${project.cardinal_components_version}")
    modImplementation include("dev.onyxstudios.cardinal-components-api:cardinal-components-entity:${project.cardinal_components_version}")
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	// Minecraft 1.18 (1.18-pre2) upwards uses Java 17.
	// it.options.release = 17
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()
}

import net.fabricmc.loom.configuration.ide.RunConfigSettings
import net.fabricmc.loom.configuration.ide.RunConfig
import net.fabricmc.loom.util.Constants

tasks.register('debugClientRenderDoc', Exec) {
	dependsOn compileJava
	dependsOn configureClientLaunch

	// slightly cursed. duplicates some of the work that loom's RunGameTask does, but not all of it.
	// i think theres some things that it handles that i dont, but it works on my machine soooooo :P
	var settings = new RunConfigSettings(project, "clientRenderDoc")
	settings.environment "client"
	settings.defaultMainClass Constants.Knot.KNOT_CLIENT
	var runConfig = RunConfig.runConfig(project, settings)

	var args = []
	args += ["renderdoccmd", "capture", "--opt-hook-children", "--opt-api-validation", "--opt-verify-buffer-access", "--opt-ref-all-resources", "-w", "-d", "$projectDir/${runConfig.runDir}"]

	var javaHome = System.properties['java.home']
	args += "$javaHome/bin/java"

	// allow ourselves to attach a debugger
	var debuggerPort = System.properties['net.xavil.debug.port']
	if (debuggerPort != null) {
		args += ["-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=$debuggerPort"]
	}

	var enhancedClassRedef = System.properties['net.xavil.debug.enhanced_class_redefinition']
	if (enhancedClassRedef != null) {
		// use enhanced class redefinition if the jvm supports it! this makes hot reloading significantly more powerful.
		args += ["-XX:+AllowEnhancedClassRedefinition", "-XX:HotswapAgent=core"]
	}

	// core arguments
	var classpath = runConfig.sourceSet.runtimeClasspath.filter { it.exists() }.each { it.absolutePath }.join ':'
	args += runConfig.vmArgs
	args += ["-cp", "$classpath", "${runConfig.mainClass}"]
	args += runConfig.programArgs

	commandLine = args
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.archivesBaseName}"}
	}
}

// configure the maven publication
publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
